server:
    servlet:
        encoding:
            force-response: true

spring:
    jpa:
        defer-datasource-initialization: true
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/earl
        username: earl
        password: han
        driver-class-name: org.postgresql.Driver
    sql:
        init:
            encoding: utf-8
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: 39acd4a4fff84f2535aa93ddb042f0c4
                        client-secret: oYWofo7GgvQfMgfAvDHXehTakpc5kf2u
                        client-authentication-method: client_secret_post
                        redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
                        authorization-grant-type: authorization_code
                        client-name: Kakao
                        scope: profile_nickname, account_email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

    servlet:
        multipart:
            location: classpath:/static/planner
            max-file-size: 5MB