server:
    servlet:
        encoding:
            force-response: true

spring:
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    datasource:
        url: {YOUR_URL}
        username: {YOUR_NAME}
        password: {YOUR_PASSWORD}
    sql:
        init:
            encoding: utf-8
            mode: never
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: {YOUR_ID}
                        client-secret: {YOUR_SECRET}
                        client-authentication-method: client_secret_post
                        redirect-uri: {YOUR_URI}
                        authorization-grant-type: authorization_code
                        client-name: Kakao
                        scope: profile_nickname, account_email
                provider:
                    kakao:
                        authorization-uri: {YOUR_URI}
                        token-uri: {YOUR_URI}
                        user-info-uri: {YOUR_URI}
                        user-name-attribute: id
    servlet:
        multipart:
            max-file-size: 5MB

jwt:
    issuer: {YOUR_EMAIL}
    secret_key: {YOUR_SECRET_KEY}